---
name: cs100-01-lab07
break: true
indent: 4
---

src/main:
    java:
        labseven/Atm.java:
            ConfirmFileExists
            CountSingleLineComments --language Java --count 5
            CountMultipleLineComments --language Java --count 2
            MatchFileFragment --fragment "@author" --count 1 --exact
            MatchFileFragment --fragment "Add Your Names Here" --count 0 --exact
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "println(" --count 10
            MatchFileFragment --fragment "if" --count 2
            MatchFileFragment --fragment "else" --count 2
            MatchFileFragment --fragment "getBalance" --count 3
            MatchFileFragment --fragment "balance" --count 1
            MatchFileFragment --fragment "withdraw" --count 1
            MatchFileFragment --fragment "deposit" --count 1
            MatchFileFragment --fragment "new Account(" --count 1
        labseven/Account.java:
            ConfirmFileExists
            CountMultipleLineComments --language Java --count 5
            MatchFileFragment --fragment "@author" --count 1 --exact
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "println(" --count 0 --exact
            MatchFileFragment --fragment "Account" --count 2
            MatchFileFragment --fragment "void deposit(" --count 1 --exact
            MatchFileFragment --fragment "void withdraw(" --count 1 --exact
            MatchFileFragment --fragment "double getBalance(" --count 1 --exact
            MatchFileFragment --fragment "return" --count 1
            MatchFileFragment --fragment "if" --count 1
        labseven/Offer.java:
            ConfirmFileExists
            CountMultipleLineComments --language Java --count 5
            MatchFileFragment --fragment "@author" --count 1 --exact
            MatchFileFragment --fragment "TODO" --count 0 --exact
            MatchFileFragment --fragment "println(" --count 0 --exact
            MatchFileFragment --fragment "Offer" --count 2
            MatchFileFragment --fragment "void setOffer(" --count 1 --exact
            MatchFileFragment --fragment "String getOfferText(" --count 1 --exact
            MatchFileFragment --fragment "int getOfferId(" --count 1 --exact
            MatchFileFragment --fragment "return" --count 1

writing/reflection.md:
    ConfirmFileExists
    CountFileWords --count 350
    CountMarkdownTags --tag "heading" --count 8 --exact
    CountMarkdownTags --tag "code" --count 3
    CountMarkdownTags --tag "code_block" --count 1 --exact
    CountMarkdownTags --tag "list" --count 2
    MatchFileFragment --fragment "Add Your Names Here" --count 0 --exact

# --> check that the number of commits in the Git repository is beyond a threshold
CountCommits --count 5

ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle -q --console plain run"
